### ISSUE TITLE
Sounds are silent - RT 5.8 (Flatpak)

### ISSUE THREAD

**Issue by arvindpgh** [pixlsus/rawtherapee-flatpak#1]
I am using Rawtherapee 5.8 (Flatpak) on Ubuntu 18.04.
The “sounds” emitted by RT after editor processing or queue processing are not working.

Here is what I checked :
The sound tab of preferences is enabled. I tried testing the default sound options like "window-attention’ on command line (canberra-gtk-play -i window-attention). They work. Nothing wrong with OS sounds.

Also, checked the options file under ~/.var/app
That file has all sound parameters specified in the sounds tab of preferences.

Sounds were working when I was using an earlier RT version from Ubuntu repository. 
It looks like the problem started when I moved to the Flatpak version.

**Comment by paperdigits** [comment]
If you installed from flathub, then the repo you want it: https://github.com/flathub/com.rawtherapee.RawTherapee

This flatpak isn't built or deployed anywhere.

**Comment by arvindpgh** [comment]
I am sorry, I don't understand.  
I do remember installing it from Flathub a few months back -- most probably from here https://flathub.org/apps/details/com.rawtherapee.RawTherapee

Could you explain what you mean?  Thanks

**Comment by paperdigits** [comment]
This isn't the right repo to report the issue in, report the issue in the repo I linked earlier.

**Comment by arvindpgh** [comment]
Oh, ok..  thanks
